-- FUNCTIONALITY > COMMENT SQL FILES (https://www.w3schools.com/sql/sql_comments.asp)
-- FUNCTIONALITY > PULLED TABLE NAMES FROM ASSIGNMENT REQUIREMENTS
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS employee;

-- NOTE > DEPARTMENT TABLE - INT AND PRIMARY KEY REQUIRED PER ASSIGNMENT
-- DOCUMENTATION > DIFFERENCE BETWEEN INT AND INTEGER (https://stackoverflow.com/questions/688582/what-is-the-difference-between-int-and-integer-in-mysql-5-0#:~:text=The%20difference%20between%20int%20and%20integer%20is%20that%20int%20is,%2C%20long%20%2C%20short%20and%20byte%20.)
-- NOTE > NOT NULL FOR NAME BECAUSE IN ORDER TO CREATE A DEPARTMENT YOU MUST NAME IT, MY LOGIC
CREATE TABLE department (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

-- NOTE > ROLE TABLE - INT AND PRIAMRY KEY REQUIRED PER ASSIGNMENT
-- NOTE > NOT NULL FOR ALL COLUMNS, ROLES MUST INCLUDE A TITLE, SALARY, AND DEPARTMENT, MY LOGIC
-- DOCUMENTATION > DECIMAL - FOR REFERENCE (https://www.mysqltutorial.org/mysql-decimal/)
CREATE TABLE roles (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) UNIQUE NOT NULL,
    salary DECIMAL NOT NULL,
    department_id INTEGER NOT NULL,
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE CASCADE
);

-- NOTE > EMPLOYEE TABLE - INT AND PRIMARY KEY REQURIED PER ASSIGNMENT
-- NOTE > NOT NULL ALL EXCEPT MANAGER ID AS REQUIRED PER ASSIGNEMNT, YOU MUST HAVE A ROLE ID AND FULL NAME, MY LOGIC
CREATE TABLE employee (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
roles_id INTEGER NOT NULL,
CONSTRAINT fk_roles FOREIGN KEY (roles_id) REFERENCES roles (id) ON DELETE CASCADE,
manager_id INTEGER,
CONSTRAINT fk_manager FOREIGN KEY (manager_id) REFERENCES employee (id) on DELETE SET NULL
);